DROP TABLE IF EXISTS public.users;

CREATE SCHEMA IF NOT EXISTS kantowork;

CREATE TABLE kantowork.users (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);
